name: frontend devops

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: frontend test
    runs-on: ubuntu-latest

    steps:
    - name: get code from github
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          sudo rm -rf devops
          sudo git clone https://github.com/hyungdoyou/devops
          cd devops
          sudo npm i
          sudo npm run build
          sudo docker build --tag hyungdoyou/fe:latest .
          sudo docker login -u ${{ secrets.DOCKER_EMAIL }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker push hyungdoyou/fe:latest
          docker-compose -f /home/ubuntu/devops.yml pull
          docker-compose -f /home/ubuntu/devops.yml up --force-recreate