name: frontend devops

on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  deploy:
    name: frontend test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: npm i
    - run: npm run build
    - run: npm test
    
    - name: result
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: 'test-results/*.xml'